require('settings')
require('settings.mappings')
require('packer-config')
require('colorscheme.tokyonight')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.nvim-tree')
require('plugins.barbar')
require('plugins.lualine')
require('plugins.truezen')
--> lsp modules
require("lsp.language-servers")
require("lsp.saga")
require("lsp.completion")
